title: Programação (2026-27)
description: Sistema de Aquisição e Monitorização de Sensores

theme: just-the-docs

markdown: kramdown

collections:
  sprints:
    output: true
    permalink: /sprints/:name/

  noticias:
    output: true
    permalink: /noticias/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page

  - scope:
      path: ""
      type: sprints
    values:
      layout: page

  - scope:
      path: ""
      type: noticias
    values:
      layout: page